#!/bin/bash

if [ "$1" == "root" ]
    then
        script="$2"
        folder=$(echo $PWD | sed -e 's/.\+\/projects\///g')
        parameters=$folder
        if [ $3 ]
            then
                parameters=${@:3}
        fi
        
        cd ../../
        ./cli $script $parameters
        cd $PWD
    exit
fi

if [ "$1" == "bootstrap" ]
    then
        ./scripts/bootstrap.sh
        exit
fi

if [ "$1" == "start" ]
    then
        ./scripts/start.sh
        exit
fi

if [ "$1" == "stop" ]
    then
        ./scripts/stop.sh
        exit
fi

if [ "$1" == "restart" ]
    then 
        ./scripts/restart.sh
        exit
fi

./scripts/app.sh $*